"""allow_multiple_producers_per_user

Revision ID: 287911cc58ce
Revises: d0420c3d8f4e
Create Date: 2026-05-04 19:49:01.215162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287911cc58ce'
down_revision = 'd0420c3d8f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_producers_owner_id'), 'producers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_producers_owner_id'), 'producers', ['owner_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
