"""add_scheduled_at and calendar_id

Revision ID: 44468f6d80d7
Revises: aff273902683
Create Date: 2026-04-22 15:49:14.510625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44468f6d80d7'
down_revision = 'aff273902683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
