"""producer_obligations_store_uuids

Revision ID: 7ca767f8cea5
Revises: b37c54b2dfde
Create Date: 2026-05-06 17:06:39.580969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca767f8cea5'
down_revision = 'b37c54b2dfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
