"""add_plan_type_company_nit_phone_invite_sent_at

Revision ID: 9f1b1cff3bf2
Revises: 44468f6d80d7
Create Date: 2026-04-23 21:14:00.765729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1b1cff3bf2'
down_revision = '44468f6d80d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. CREAR EL TIPO ENUM MANUALMENTE (Esto es lo que faltaba)
    # Definimos el objeto Enum con su nombre y valores
    plan_type_enum = sa.Enum('demo_rep', 'demo_indv', 'demo_col', 'demo_esg', name='plantype')
    # Ejecutamos la creación en la base de datos
    plan_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('contact_requests', sa.Column('invite_sent', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('plan_type', sa.Enum('demo_rep', 'demo_indv', 'demo_col', 'demo_esg', name='plantype'), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('nit', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'nit')
    op.drop_column('users', 'company')
    op.drop_column('users', 'plan_type')
    op.drop_column('contact_requests', 'invite_sent')

    # 2. ELIMINAR EL TIPO ENUM (Para que la base de datos quede limpia si haces rollback)
    sa.Enum(name='plantype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###