"""add_scheduled_at_calendar_event_id_to_contact_requests

Revision ID: aff273902683
Revises: b4771b72f391
Create Date: 2026-04-21 13:04:28.416143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff273902683'
down_revision = 'b4771b72f391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_requests', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contact_requests', sa.Column('calendar_event_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_requests', 'calendar_event_id')
    op.drop_column('contact_requests', 'scheduled_at')
    # ### end Alembic commands ###
