"""add_other_sector_producers

Revision ID: b37c54b2dfde
Revises: 287911cc58ce
Create Date: 2026-05-06 16:30:40.896148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37c54b2dfde'
down_revision = '287911cc58ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producers', sa.Column('other_sector', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producers', 'other_sector')
    # ### end Alembic commands ###
