"""producer_obligations_relation

Revision ID: c9efc60db78e
Revises: 7ca767f8cea5
Create Date: 2026-05-06 12:34:34.334276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9efc60db78e'
down_revision = '7ca767f8cea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer_obligations',
    sa.Column('producer_id', sa.Uuid(), nullable=False),
    sa.Column('obligation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['normative_obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producer_id', 'obligation_id')
    )
    op.drop_column('producers', 'obligaciones_normativas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producers', sa.Column('obligaciones_normativas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('producer_obligations')
    # ### end Alembic commands ###
