"""Modify_add_contact_requests

Revision ID: fcfe6374e465
Revises: 6578fd6abf97
Create Date: 2026-04-18 18:12:58.018354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcfe6374e465'
down_revision = '6578fd6abf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_requests', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('contact_requests_reviewed_by_id_fkey'), 'contact_requests', type_='foreignkey')
    op.create_foreign_key(None, 'contact_requests', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_requests', type_='foreignkey')
    op.create_foreign_key(op.f('contact_requests_reviewed_by_id_fkey'), 'contact_requests', 'users', ['reviewed_by_id'], ['id'])
    op.alter_column('contact_requests', 'reviewed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
